### ISSUE TITLE
quickSend代码有问题

### ISSUE THREAD

**Issue by chmis8000** [wxpusher/wxpusher-sdk-php#6]
'content' => urlencode($content)
不该做url编码，导致汉字无法正常发送

**Comment by meloncn** [comment]
@chmis8000   你好，作者文档中针对GET请求传递参数中有说明：请求参数：appToken、uid、topicId、content、url ，其中content和url请进行urlEncode编码。出自：https://wxpusher.dingliqc.com/docs/#/

**Comment by interestingcn** [comment]
@chmis8000 你好，按照文档要求该字段应该url编码后发送。今晚测试后发现确实存在问题已修复并PR等待合并分支。

**Comment by i-chenzhe** [comment]
> 'content' => urlencode($content)
> 不该做url编码，导致汉字无法正常发送

这两天正好用到这部分，在$data中的content的确不需要做urlencode，在$result的json_decode中可以添加一个option为256，就可以解决中文被unioncode的问题。

**Comment by sir-i-do** [comment]
> 'content' => urlencode($content)
> 不该做url编码，导致汉字无法正常发送

这两天正好用到这部分。我是通过curl来操作的，在$data部分我是不尽兴urlencode的，而是在postfiles中传入json_encode($data,256)，这样的方式来完成的。这样中文就可以正常发送并在客户端显示了。

**Comment by meloncn** [comment]
谢谢您的提醒！！啊啊啊我要甩锅给文档了555




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wxpusher/wxpusher-sdk-php"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月7日(星期一) 中午1:08
收件人:&nbsp;"wxpusher/wxpusher-sdk-php"<wxpusher-sdk-php@noreply.github.com&gt;;
抄送:&nbsp;"Meloncn"<1430567640@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [wxpusher/wxpusher-sdk-php] quickSend代码有问题 (#6)





  
'content' =&gt; urlencode($content)
 不该做url编码，导致汉字无法正常发送
  
这两天正好用到这部分，在$data中的content的确不需要做urlencode，在$result的json_decode中可以添加一个option为256，就可以解决中文被unioncode的问题。

**Comment by interestingcn** [comment]
感谢老师教导，我会尽快修改此问题！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wxpusher/wxpusher-sdk-php"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月7日(星期一) 中午1:13
收件人:&nbsp;"wxpusher/wxpusher-sdk-php"<wxpusher-sdk-php@noreply.github.com&gt;;
抄送:&nbsp;"Meloncn"<1430567640@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [wxpusher/wxpusher-sdk-php] quickSend代码有问题 (#6)





  
'content' =&gt; urlencode($content)
 不该做url编码，导致汉字无法正常发送
  
这两天正好用到这部分。我是通过curl来操作的，在$data部分我是不尽兴urlencode的，而是在postfiles中传入json_encode($data,256)，这样的方式来完成的。这样中文就可以正常发送并在客户端显示了。

**Comment by sir-i-do** [comment]
> 感谢老师教导，我会尽快修改此问题！
> […](#)
不敢说教导，我也是在自学php。
对github不太懂操作，我自己写了一个类库，大部分是参考了你的内容，可以去看看参考一下。
https://github.com/i-chenzhe/weChatPusher--PHP
